# Első szakasz: Build szakasz

FROM golang:1.23.3-bookworm AS build

COPY ./golangwebapp/* /golangwebapp/

WORKDIR /golangwebapp

RUN go build

# Második szakasz: Runtime szakasz

FROM golang:1.23.3-bookworm

COPY --from=build /golangwebapp/webappdemo /app/webappdemo

WORKDIR /app

EXPOSE 5000

CMD ["./webappdemo"]