# Alap image HTTPD-hez

FROM httpd:latest


COPY index.html /usr/local/apache2/htdocs

RUN sed -i 's/^Listen 80*/Listen 8080/' /usr/local/apache2/conf/httpd.conf


EXPOSE 80


CMD ["httpd-foreground"]

